/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 123
#define YY_END_OF_BUFFER 124
static yyconst short int yy_acclist[453] =
    {   0,
      105,  105,  124,  122,  123,  123,   70,  122,  123,   83,
      122,  123,  102,  122,  123,   43,  122,  123,   62,  122,
      123,   77,  122,  123,   78,  122,  123,   41,  122,  123,
       39,  122,  123,   76,  122,  123,   40,  122,  123,   75,
      122,  123,   42,  122,  123,  107,  117,  122,  123,  107,
      108,  117,  122,  123,   74,  122,  123,   48,  122,  123,
       55,  122,  123,   47,  122,  123,  122,  123,  122,  123,
      121,  122,  123,  121,  122,  123,  121,  122,  123,   81,
      122,  123,   82,  122,  123,   64,  122,  123,  118,  122,
      123,  118,  122,  123,  118,  122,  123,  118,  122,  123,

      118,  122,  123,  118,  122,  123,  118,  122,  123,  118,
      122,  123,  118,  122,  123,  118,  122,  123,  118,  122,
      123,  118,  122,  123,  118,  122,  123,  118,  122,  123,
      118,  122,  123,  118,  122,  123,  118,  122,  123,   79,
      122,  123,   63,  122,  123,   80,  122,  123,   65,  122,
      123,   55,  122,  123,  105,  123,  105,  123,   85,  123,
      101,  123,   86,  123,  123,   86,  123,   46,  102,   60,
       68,   44,   58,   56,   57,   72,   59,  107,  106,  107,
      111,  112,  107,  107,  108,  117,  108,   66,   50,   45,
       49,   67,   71,  119,  121,  121,  121,  118,  118,  118,

      118,  118,  118,  118,  118,   10,  118,  118,  118,  118,
      118,  118,   18,  118,   19,  118,  118,  118,  118,  118,
       24,  118,  118,  118,  118,  118,  118,  118,  118,  118,
       69,  105,  105,   85,   84,   97,   98,   96,   88,   89,
       94,   92,   87,   93,   95,   90,   91,  100,   61,   73,
      117,  107,  106,  107,  111,  112,  112,  115,  116,  110,
      117,  111,  112,  113,  114,  107,  112,  107,  107,  108,
      117,  108,   51,   52,  120,  119,  121,   13,  121,  118,
        2,  118,  118,  118,  118,  118,    8,  118,  118,   14,
      118,  118,  118,  118,  118,   17,  118,  118,  118,   22,

      118,   23,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  105,   98,  100,   99,
      106,  107,  111,  112,  112,  115,  116,  116,  116,  109,
      110,  110,  110,  111,  112,  112,  112,  113,  114,  114,
      114,  107,  112,  112,  108,  120,  121,  118,  118,  118,
        6,  118,  118,  118,   11,  118,  118,  118,   53,  118,
      118,  118,   21,  118,   25,  118,  118,  118,  118,   29,
      118,  118,   31,  118,   32,  118,  118,  118,  118,   36,
      118,  118,  118,  104,  105,   98,   99,  117,  112,  115,
      116,  116,  116,  110,  110,  117,  111,  112,  113,  114,

      114,  114,    3,  121,    1,  118,    4,  118,    5,  118,
        7,  118,  118,   12,  118,  118,  118,   16,  118,  118,
      118,   27,  118,  118,   30,  118,   33,  118,  118,   35,
      118,   37,  118,   38,  118,  109,  110,  118,   15,  118,
       54,   20,  118,   26,  118,   28,  118,   34,  118,  103,
      118,    9
    } ;

static yyconst short int yy_accept[313] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    4,    6,    7,
       10,   13,   16,   19,   22,   25,   28,   31,   34,   37,
       40,   43,   46,   50,   55,   58,   61,   64,   67,   69,
       71,   74,   77,   80,   83,   86,   89,   92,   95,   98,
      101,  104,  107,  110,  113,  116,  119,  122,  125,  128,
      131,  134,  137,  140,  143,  146,  149,  152,  155,  157,
      159,  161,  163,  165,  166,  168,  169,  170,  171,  172,
      173,  174,  175,  176,  177,  178,  179,  183,  184,  184,
      184,  184,  184,  184,  184,  187,  188,  189,  190,  191,
      192,  193,  194,  194,  195,  196,  197,  198,  199,  200,

      201,  202,  203,  204,  205,  206,  208,  209,  210,  211,
      212,  213,  215,  217,  218,  219,  220,  221,  223,  224,
      225,  226,  227,  228,  229,  230,  231,  232,  232,  233,
      234,  235,  236,  237,  238,  239,  240,  241,  242,  243,
      244,  245,  246,  247,  248,  249,  250,  251,  252,  253,
      257,  258,  258,  260,  260,  261,  261,  261,  262,  264,
      264,  266,  266,  268,  269,  269,  269,  269,  269,  269,
      272,  273,  274,  275,  276,  277,  278,  280,  281,  283,
      284,  285,  286,  287,  289,  290,  292,  293,  294,  295,
      296,  298,  299,  300,  302,  304,  305,  306,  307,  308,

      309,  310,  311,  312,  313,  314,  315,  316,  317,  317,
      318,  319,  320,  321,  321,  325,  326,  328,  329,  330,
      332,  333,  334,  334,  336,  337,  338,  340,  341,  342,
      344,  345,  346,  347,  348,  349,  350,  351,  353,  354,
      355,  357,  358,  359,  360,  361,  362,  363,  365,  367,
      368,  369,  370,  372,  373,  375,  377,  378,  379,  380,
      382,  383,  384,  384,  386,  387,  388,  389,  390,  392,
      393,  394,  395,  396,  397,  399,  401,  402,  403,  405,
      407,  409,  411,  413,  414,  416,  417,  418,  420,  421,
      422,  424,  425,  427,  429,  430,  432,  434,  436,  436,

      438,  439,  441,  442,  444,  446,  448,  450,  451,  452,
      453,  453
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,    1,   21,
       22,   23,   24,   25,   26,   27,   26,   28,   29,   26,
       30,   31,   32,   31,   31,   31,   31,   33,   34,   31,
       31,   31,   31,   31,   31,   31,   31,   35,   31,   31,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   50,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[70] =
    {   0,
        1,    2,    1,    3,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    5,    1,
        1,    1,    1,    1,    6,    5,    5,    5,    5,    7,
        7,    7,    7,    7,    7,    1,    4,    1,    1,    8,
        9,    9,    9,    9,    9,    9,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,    4,    1,    4,    1
    } ;

static yyconst short int yy_base[330] =
    {   0,
        0,  663,  682,   68,   69,   73,  683,  686,  686,  660,
      686,    0,  659,  673,  686,  686,   62,  657,  686,  656,
      663,  654,  128,   69,  686,   58,  653,   59,  654,  648,
        0,  643,  636,  686,  686,  686,    0,   37,   47,   52,
       52,   42,   60,   49,  613,   63,  606,  618,   55,   63,
      606,  611,  609,  686,  585,  686,  686,   80,    0,  603,
        0,  686,  581,  189,  686,  686,    0,  686,  686,  621,
      686,  686,  686,  628,  686,  107,  113,  160,  103,  131,
      148,  164,  593,  238,  170,  178,  686,  609,  604,  686,
      686,  686,    0,    0,    0,  589,  590,    0,  561,  565,

      561,  553,  533,  545,  535,    0,  512,   69,   99,  496,
      489,    0,    0,  502,  481,  492,  483,    0,  131,  489,
      484,  494,  476,  157,   89,  491,  686,  490,    0,  479,
        0,  686,  686,  195,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  287,  686,  686,  223,  686,  205,
      243,  258,  254,  268,  270,  210,  279,  301,  283,  308,
      492,  491,  320,  326,  295,  332,  336,  490,  339,  345,
      351,  686,  686,    0,    0,  497,    0,  482,    0,  473,
      467,  462,  446,  449,   91,    0,  436,  472,  453,  434,
        0,  431,  430,    0,    0,  434,  431,  175,  415,  409,

      399,  402,  401,  391,  360,  344,  345,  344,  334,  331,
      274,  376,    0,  361,  370,  383,  366,  391,  395,  397,
      408,  422,  426,  412,  416,  433,  333,  331,  325,  441,
      447,  451,    0,  314,  287,  273,  271,    0,  262,  255,
        0,  261,  223,  686,  227,  224,  215,    0,    0,  203,
      193,  188,    0,  186,    0,    0,  192,  178,  180,    0,
      180,  176,  167,    0,  686,  686,  459,  466,  455,  463,
      469,  494,  498,  502,  484,  174,  168,  163,    0,    0,
        0,    0,    0,  157,    0,  153,  161,    0,  124,  113,
        0,  100,    0,    0,   93,    0,    0,    0,   79,  509,

       73,    0,  686,    0,    0,    0,    0,  686,   52,  686,
      686,  549,  559,  569,  574,  580,  586,  596,  606,  612,
      614,  620,  630,  636,  641,  646,  652,  657,  662
    } ;

static yyconst short int yy_def[330] =
    {   0,
      311,    1,  312,  312,  313,  313,  311,  311,  311,  311,
      311,  314,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  315,
      316,  316,  316,  311,  311,  311,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  311,  311,  311,  311,  311,  318,  318,
      319,  311,  311,  311,  311,  311,  314,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  320,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  321,  322,  316,  316,  316,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  311,  311,  318,  318,
      319,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  323,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      324,  325,  311,  311,  311,  311,  311,  325,   84,  311,
      311,  311,  311,  326,  322,  316,  316,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  311,  318,
      311,  323,  327,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  324,  328,  329,  311,
      311,  311,  326,  316,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  311,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  311,  318,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  328,  329,  329,  316,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  311,  311,

      317,  317,  311,  317,  317,  317,  317,  311,  317,  311,
        0,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311
    } ;

static yyconst short int yy_nxt[756] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   31,   33,   31,
       31,   31,   31,   31,   31,   34,    8,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   37,   37,   44,   37,
       37,   37,   45,   46,   47,   37,   37,   48,   49,   50,
       51,   37,   52,   37,   53,   54,   55,   56,   57,    9,
        9,   70,   62,   63,    9,  310,   62,   63,   87,   88,
       90,   91,   76,   71,   85,   85,   85,   85,   99,   60,
      100,  101,  103,  107,  112,  108,  105,   81,  109,  120,

      110,   89,  113,  104,  102,   64,  106,  115,   86,   64,
      122,  116,  186,   81,  111,  121,  309,  117,  153,  153,
      123,  128,  148,  148,  148,  148,  149,  187,  150,  150,
      150,   78,  308,  206,   65,  241,   65,  207,   65,  242,
       65,   76,  154,   77,   77,   77,   78,  155,  155,  155,
      188,  307,  151,  306,   79,   80,   81,  305,  157,  189,
      157,   82,   83,  158,  158,  158,  158,   84,  304,   79,
      156,   80,   81,  149,  196,   78,   78,   78,   78,  159,
      159,  159,   82,   76,  303,   85,   85,   85,   85,  197,
      198,   83,  133,  170,  170,  170,  170,  302,   81,  152,

      203,  301,  277,  160,  134,  134,  134,  277,  204,   86,
      211,  211,  211,  228,   81,  299,  205,  171,  149,  298,
      150,  150,  150,   78,  297,  135,  222,  222,  222,  136,
      137,  296,  251,  138,  139,  252,  295,  294,  148,  148,
      148,  148,  140,  293,  151,  292,  141,  142,  143,  156,
      144,   81,  145,  163,  163,  163,  164,  291,  215,  215,
      215,  164,  214,  290,  165,  166,  289,   81,  288,  217,
      217,  167,  168,  164,  164,  164,  164,  169,  287,  165,
      286,  166,  216,  219,  219,  220,  220,  220,  220,  265,
      265,  265,  167,  218,  158,  158,  158,  158,  224,  224,

      224,  168,  213,  213,  213,  213,  285,  154,  284,  221,
      219,  219,  213,  213,  213,  213,  158,  158,  158,  158,
      283,  282,  225,  226,  226,  226,  281,  213,  213,  213,
      213,  213,  213,  149,  154,  230,  230,  230,  164,  149,
      223,  164,  164,  164,  164,  280,  279,  160,  222,  222,
      222,  226,  226,  226,  226,  226,  226,  311,   76,  231,
      170,  170,  170,  170,  277,  152,  232,  232,  232,  232,
      277,  156,  228,   81,  264,  160,  267,  267,  267,  267,
      263,  217,  217,  149,   86,  215,  215,  215,  164,   81,
      171,  311,  311,  311,  311,  262,  261,  260,  268,  268,

      268,  311,  311,  311,  311,  218,  269,  269,  259,  151,
      271,  271,  220,  220,  220,  220,  311,  311,  311,  311,
      311,  311,  216,  273,  273,  273,  273,  224,  224,  224,
      270,  275,  275,  275,  270,  258,  272,  273,  273,  273,
      273,  274,  274,  274,  274,  257,  256,  221,  268,  268,
      268,  225,  255,  254,  149,  216,  230,  230,  230,  164,
      253,  221,  230,  230,  230,  164,  232,  232,  232,  232,
      269,  269,  216,  250,  267,  267,  267,  267,  271,  271,
      231,  268,  268,  268,  271,  271,  216,   81,  249,  248,
      171,  247,  246,  245,  218,  244,  243,  240,  214,  275,

      275,  275,  270,   81,  239,  216,  238,  237,  270,  300,
      300,  300,  300,  273,  273,  273,  273,  274,  274,  274,
      274,  236,  235,  225,  300,  300,  300,  300,  234,  162,
      162,  228,  210,  221,  209,  208,  202,  221,  201,  200,
      199,  223,  195,  194,  193,  192,  191,  190,  272,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   67,
      185,   67,   67,   67,   67,   67,   67,   67,   67,   94,
      184,   94,   94,   94,   95,  183,   95,   95,   95,   95,
       98,  182,   98,   98,   98,   98,  129,  181,  129,  129,

      129,  129,  129,  129,  129,  129,  131,  180,  179,  178,
      131,  131,  131,  131,  131,  131,  161,  177,  176,  161,
      161,  174,  174,  174,  175,  173,  175,  175,  175,  175,
      212,  172,  162,  212,  212,  212,  212,  212,  212,  212,
      227,  147,  146,  227,  227,  229,  132,  130,  229,  229,
      233,  127,  233,  233,  233,  233,  266,  126,  125,  124,
      266,  276,  119,  118,  276,  276,  278,  114,   97,  278,
      278,   96,   93,   92,   89,   75,   74,   73,   72,   69,
       68,   66,  311,    9,   58,    7,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311
    } ;

static yyconst short int yy_chk[756] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        5,   17,    5,    5,    6,  309,    6,    6,   26,   26,
       28,   28,   24,   17,   24,   24,   24,   24,   38,    4,
       38,   39,   40,   42,   44,   42,   41,   24,   42,   49,

       43,   58,   44,   40,   39,    5,   41,   46,   24,    6,
       50,   46,  108,   24,   43,   49,  301,   46,   79,   79,
       50,   58,   76,   76,   76,   76,   77,  108,   77,   77,
       77,   77,  299,  125,    5,  185,    5,  125,    6,  185,
        6,   23,   79,   23,   23,   23,   23,   80,   80,   80,
      109,  295,   77,  292,   23,   23,   23,  290,   81,  109,
       81,   23,   23,   81,   81,   81,   81,   23,  289,   23,
       80,   23,   23,   78,  119,   78,   78,   78,   78,   82,
       82,   82,   23,   85,  287,   85,   85,   85,   85,  119,
      119,   23,   64,   86,   86,   86,   86,  286,   85,   78,

      124,  284,  278,   82,   64,   64,   64,  277,  124,   85,
      134,  134,  134,  276,   85,  263,  124,   86,  150,  262,
      150,  150,  150,  150,  261,   64,  156,  156,  156,   64,
       64,  259,  198,   64,   64,  198,  258,  257,  148,  148,
      148,  148,   64,  254,  150,  252,   64,   64,   64,  156,
       64,  148,   64,   84,   84,   84,   84,  251,  151,  151,
      151,  151,  148,  250,   84,   84,  247,  148,  246,  153,
      153,   84,   84,  152,  152,  152,  152,   84,  245,   84,
      243,   84,  151,  154,  154,  155,  155,  155,  155,  211,
      211,  211,   84,  153,  157,  157,  157,  157,  159,  159,

      159,   84,  145,  145,  145,  145,  242,  154,  240,  155,
      165,  165,  145,  145,  145,  145,  158,  158,  158,  158,
      239,  237,  159,  160,  160,  160,  236,  145,  145,  145,
      145,  145,  145,  163,  165,  163,  163,  163,  163,  164,
      158,  164,  164,  164,  164,  235,  234,  160,  166,  166,
      166,  167,  167,  167,  169,  169,  169,  169,  170,  163,
      170,  170,  170,  170,  229,  164,  171,  171,  171,  171,
      228,  166,  227,  170,  210,  167,  214,  214,  214,  214,
      209,  217,  217,  215,  170,  215,  215,  215,  215,  170,
      171,  212,  212,  212,  212,  208,  207,  206,  216,  216,

      216,  212,  212,  212,  212,  217,  218,  218,  205,  215,
      219,  219,  220,  220,  220,  220,  212,  212,  212,  212,
      212,  212,  216,  221,  221,  221,  221,  224,  224,  224,
      218,  225,  225,  225,  219,  204,  220,  222,  222,  222,
      222,  223,  223,  223,  223,  203,  202,  221,  226,  226,
      226,  224,  201,  200,  230,  225,  230,  230,  230,  230,
      199,  222,  231,  231,  231,  231,  232,  232,  232,  232,
      269,  269,  226,  197,  267,  267,  267,  267,  270,  270,
      230,  268,  268,  268,  271,  271,  231,  267,  196,  193,
      232,  192,  190,  189,  269,  188,  187,  184,  267,  275,

      275,  275,  270,  267,  183,  268,  182,  181,  271,  272,
      272,  272,  272,  273,  273,  273,  273,  274,  274,  274,
      274,  180,  178,  275,  300,  300,  300,  300,  176,  168,
      162,  161,  130,  272,  128,  126,  123,  273,  122,  121,
      120,  274,  117,  116,  115,  114,  111,  110,  300,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  314,
      107,  314,  314,  314,  314,  314,  314,  314,  314,  315,
      105,  315,  315,  315,  316,  104,  316,  316,  316,  316,
      317,  103,  317,  317,  317,  317,  318,  102,  318,  318,

      318,  318,  318,  318,  318,  318,  319,  101,  100,   99,
      319,  319,  319,  319,  319,  319,  320,   97,   96,  320,
      320,  321,  321,  321,  322,   89,  322,  322,  322,  322,
      323,   88,   83,  323,  323,  323,  323,  323,  323,  323,
      324,   74,   70,  324,  324,  325,   63,   60,  325,  325,
      326,   55,  326,  326,  326,  326,  327,   53,   52,   51,
      327,  328,   48,   47,  328,  328,  329,   45,   33,  329,
      329,   32,   30,   29,   27,   22,   21,   20,   18,   14,
       13,   10,    7,    3,    2,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "RubyLexer.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 6 "RubyLexer.l"
	#include <stdio.h> 
    #include <string.h>   

    void removeCharacterFromString(const char * str, char * dest, char deleted_char);
    int btoi(const char * str);
#define ML_COMMENT 1

#define STRING 2

#line 712 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 28 "RubyLexer.l"


   
    int num;
    float real_num;
    char temp1[100];
    char temp2[100];
    char comment[1000];
    char string[1000];
    int concatenation = 0;


#line 879 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 312 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 686 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 40 "RubyLexer.l"
{ printf("Keyword: alias\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "RubyLexer.l"
{ printf("Keyword: and\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "RubyLexer.l"
{ printf("Keyword: BEGIN\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "RubyLexer.l"
{ printf("Keyword: begin\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "RubyLexer.l"
{ printf("Keyword: break\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "RubyLexer.l"
{ printf("Keyword: case\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "RubyLexer.l"
{ printf("Keyword: class\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "RubyLexer.l"
{ printf("Keyword: def\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "RubyLexer.l"
{ printf("Keyword: defined?\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "RubyLexer.l"
{ printf("Keyword: do\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "RubyLexer.l"
{ printf("Keyword: else\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "RubyLexer.l"
{ printf("Keyword: elsif\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "RubyLexer.l"
{ printf("Keyword: END\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "RubyLexer.l"
{ printf("Keyword: end\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "RubyLexer.l"
{ printf("Keyword: ensure\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "RubyLexer.l"
{ printf("Keyword: false\n"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "RubyLexer.l"
{ printf("Keyword: for\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "RubyLexer.l"
{ printf("Keyword: if\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "RubyLexer.l"
{ printf("Keyword: in\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "RubyLexer.l"
{ printf("Keyword: module\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "RubyLexer.l"
{ printf("Keyword: next\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "RubyLexer.l"
{ printf("Keyword: nil\n"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "RubyLexer.l"
{ printf("Keyword: not\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "RubyLexer.l"
{ printf("Keyword: or\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "RubyLexer.l"
{ printf("Keyword: redo\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "RubyLexer.l"
{ printf("Keyword: rescue\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "RubyLexer.l"
{ printf("Keyword: retry\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "RubyLexer.l"
{ printf("Keyword: return\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "RubyLexer.l"
{ printf("Keyword: self\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "RubyLexer.l"
{ printf("Keyword: super\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "RubyLexer.l"
{ printf("Keyword: then\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "RubyLexer.l"
{ printf("Keyword: true\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "RubyLexer.l"
{ printf("Keyword: undef\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "RubyLexer.l"
{ printf("Keyword: unless\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "RubyLexer.l"
{ printf("Keyword: until\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "RubyLexer.l"
{ printf("Keyword: when\n"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "RubyLexer.l"
{ printf("Keyword: while\n"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "RubyLexer.l"
{ printf("Keyword: yield\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "RubyLexer.l"
{ printf("Operator: +\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "RubyLexer.l"
{ printf("Operator: -\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "RubyLexer.l"
{ printf("Operator: *\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "RubyLexer.l"
{ printf("Operator: /\n"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "RubyLexer.l"
{ printf("Operator: %\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "RubyLexer.l"
{ printf("Operator: **\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 86 "RubyLexer.l"
{ printf("Operator: ==\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 87 "RubyLexer.l"
{ printf("Operator: !=\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 88 "RubyLexer.l"
{ printf("Operator: >\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 89 "RubyLexer.l"
{ printf("Operator: <\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 90 "RubyLexer.l"
{ printf("Operator: >=\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "RubyLexer.l"
{ printf("Operator: <=\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "RubyLexer.l"
{ printf("Operator: <=>\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "RubyLexer.l"
{ printf("Operator: ===\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "RubyLexer.l"
{ printf("Operator: eql?\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 "RubyLexer.l"
{ printf("Operator: equal?\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "RubyLexer.l"
{ printf("Operator: =\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "RubyLexer.l"
{ printf("Operator: +=\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "RubyLexer.l"
{ printf("Operator: -=\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "RubyLexer.l"
{ printf("Operator: *=\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "RubyLexer.l"
{ printf("Operator: /=\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "RubyLexer.l"
{ printf("Operator: %=\n"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "RubyLexer.l"
{ printf("Operator: **=\n"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "RubyLexer.l"
{ printf("Operator: &\n"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "RubyLexer.l"
{ printf("Operator: |\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "RubyLexer.l"
{ printf("Operator: ^\n"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "RubyLexer.l"
{ printf("Operator: ~\n"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "RubyLexer.l"
{ printf("Operator: <<\n"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "RubyLexer.l"
{ printf("Operator: >>\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 112 "RubyLexer.l"
{ printf("Operator: &&\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 113 "RubyLexer.l"
{ printf("Operator: ||\n"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 114 "RubyLexer.l"
{ printf("Operator: !\n"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "RubyLexer.l"
{ printf("Operator: ?:\n"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 118 "RubyLexer.l"
{ printf("Operator: ..\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 119 "RubyLexer.l"
{ printf("Operator: ...\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 121 "RubyLexer.l"
{ printf("Sign: :\n"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 122 "RubyLexer.l"
{ printf("Sign: .\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 123 "RubyLexer.l"
{ printf("Sign: ,\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 124 "RubyLexer.l"
{ printf("Bracket: (\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 125 "RubyLexer.l"
{ printf("Bracket: )\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 126 "RubyLexer.l"
{ printf("Bracket: {\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 127 "RubyLexer.l"
{
                if(concatenation == 0) {
                    printf("Bracket: }\n");
                } else {
                    concatenation--;
                    BEGIN(STRING);
                    string[0] = 0;
                    printf("Found concatenation with string\n");
                }
            }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 137 "RubyLexer.l"
{ printf("Bracket: [\n"); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 138 "RubyLexer.l"
{ printf("Bracket: ]\n"); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 140 "RubyLexer.l"
{ 
                string[0] = 0; 
                BEGIN(STRING);    
            }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 145 "RubyLexer.l"
{ 
                        printf("String: %s\n", string);
                        printf("Found concatenation with string\n");
                        concatenation++;
                        BEGIN(INITIAL);
                    }            
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 152 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 153 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 154 "RubyLexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 155 "RubyLexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 156 "RubyLexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 157 "RubyLexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 158 "RubyLexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 159 "RubyLexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 160 "RubyLexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 161 "RubyLexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 162 "RubyLexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 163 "RubyLexer.l"
{ strcat(string, "\\"); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 164 "RubyLexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 165 "RubyLexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 172 "RubyLexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 178 "RubyLexer.l"
{ printf("ERROR: invalid hex escape \n"); } 
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 179 "RubyLexer.l"
{ printf("ERROR: expected \" \n");}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 180 "RubyLexer.l"
{ printf("String: %s\n", string); BEGIN(INITIAL); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 182 "RubyLexer.l"
{ printf("Single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 184 "RubyLexer.l"
{                                     
                            comment[0] = 0; 
                            BEGIN(ML_COMMENT);
                        }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 189 "RubyLexer.l"
{
                            strcat(comment, yytext+4);
                            printf("Multi-line comment: %s\n", comment);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 195 "RubyLexer.l"
{ 
                            strcat(comment, yytext); 
                        }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 199 "RubyLexer.l"
{ 
                            printf("expected =end"); BEGIN(INITIAL); 
                        }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 203 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 1,temp1,'_');
                                num = strtoll(temp1, NULL, 8);
                                printf("Binary number: %d\n", num); 
                            }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 209 "RubyLexer.l"
{ 
                                removeCharacterFromString(yytext,temp1,'_');
                                num = atoi(temp1);
                                printf("Decimal number: %d\n", num);
                            }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 215 "RubyLexer.l"
{ printf("ERROR: invalid decimal number: %s\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 217 "RubyLexer.l"
{
                                removeCharacterFromString(yytext+2,temp1,'_');
                                num = atoi(temp1);
                                printf("Decimal number: %d\n", num);              
                            }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 223 "RubyLexer.l"
{ printf("ERROR: invalid decimal number with dD: %s\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 225 "RubyLexer.l"
{
                                removeCharacterFromString(yytext,temp1,'_');
                                removeCharacterFromString(temp1,temp2,'o');
                                removeCharacterFromString(temp2,temp1,'O');
                                sscanf(temp1,"%o",&num);
                                printf("Octal number: %d\n", num);
                            }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 233 "RubyLexer.l"
{ printf("ERROR: invalid octal number: %s\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 235 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                sscanf(temp1,"%x",&num);
                                printf("Hexadecimal number: %d\n", num);
                            }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 241 "RubyLexer.l"
{ printf("ERROR: invalid hexadecimal number: %s\n", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 243 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                num = btoi(temp1);
                                printf("Binary number: %d\n", num); 
                            }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 249 "RubyLexer.l"
{ printf("ERROR: invalid binary number: %s\n", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 252 "RubyLexer.l"
{
                                                                 removeCharacterFromString(yytext,temp1,'_'); 
                                                                 real_num = atof(temp1);                                                                
                                                                 printf("Float number: %f\n", real_num); 
                                                            }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 258 "RubyLexer.l"
{
                                                printf("Local variable or method name: %s\n", yytext);
                                            }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 262 "RubyLexer.l"
{
                                                printf("Instance variable: %s\n", yytext);
                                            }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 266 "RubyLexer.l"
{
                                                printf("Class variable: %s\n", yytext);
                                            }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 270 "RubyLexer.l"
{
                                                printf("Class name: %s\n", yytext);
                                            }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 274 "RubyLexer.l"
{}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 276 "RubyLexer.l"
ECHO;
	YY_BREAK
#line 1670 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 312 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 312 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 311);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 276 "RubyLexer.l"


void removeCharacterFromString(const char * str, char * dest, char deleted_char) {
	int j = 0;
	
    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int btoi(const char * str) {
    const char *p = str;
    unsigned int   r = 0;

    while (p && *p ) {
        r <<= 1;
        r += (unsigned int)((*p++) & 0x01);
    }

    return (int) r;
}

int main(int argc, char **argv ){
	yyin = fopen(argv[1], "r" );

    yylex();
    return 0;
}
