/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
static yyconst short int yy_acclist[353] =
    {   0,
       77,   77,   96,   94,   95,   44,   95,   41,   94,   95,
       55,   94,   95,   74,   94,   95,   28,   94,   95,   94,
       95,   48,   94,   95,   49,   94,   95,   26,   94,   95,
       24,   94,   95,   46,   94,   95,   25,   94,   95,   45,
       94,   95,   27,   94,   95,   79,   89,   94,   95,   79,
       80,   89,   94,   95,   47,   94,   95,   33,   94,   95,
       38,   94,   95,   32,   94,   95,   54,   94,   95,   93,
       94,   95,   52,   94,   95,   53,   94,   95,   90,   94,
       95,   90,   94,   95,   90,   94,   95,   90,   94,   95,
       90,   94,   95,   90,   94,   95,   90,   94,   95,   90,

       94,   95,   90,   94,   95,   90,   94,   95,   90,   94,
       95,   90,   94,   95,   90,   94,   95,   90,   94,   95,
       90,   94,   95,   50,   94,   95,   94,   95,   51,   94,
       95,   38,   94,   95,   77,   95,   95,   77,   95,   57,
       95,   73,   95,   58,   95,   95,   58,   95,   31,   74,
       39,   29,   42,   79,   78,   79,   83,   84,   79,   79,
       80,   89,   80,   35,   30,   34,   91,   93,   90,   90,
       90,   90,   90,    7,   90,   90,   90,   90,   90,    8,
       90,   14,   90,   90,   90,   16,   90,   90,   90,   90,
       90,   90,   90,   90,   40,   77,   77,   57,   56,   69,

       70,   68,   60,   61,   66,   64,   59,   65,   67,   62,
       63,   72,   43,   89,   79,   78,   79,   83,   84,   84,
       87,   88,   82,   89,   83,   84,   85,   86,   79,   84,
       79,   79,   80,   89,   80,   36,   37,   92,   91,    1,
       90,   90,   90,    5,   90,   90,   11,   90,   90,   13,
       90,    4,   90,   15,   90,   90,   90,   90,   90,   90,
       90,   90,   77,   70,   72,   71,   78,   79,   83,   84,
       84,   87,   88,   88,   88,   81,   82,   82,   82,   83,
       84,   84,   84,   85,   86,   86,   86,   79,   84,   84,
       80,   92,   90,   90,   90,    9,   90,   90,   90,   90,

       18,   90,   90,   20,   90,   21,   90,   90,   90,   76,
       77,   70,   71,   89,   84,   87,   88,   88,   88,   82,
       82,   89,   83,   84,   85,   86,   86,   86,    2,   90,
        3,   90,   90,   10,   90,   12,   90,   90,   19,   90,
       22,   90,   23,   90,   81,   82,   90,   17,   90,   75,
       90,    6
    } ;

static yyconst short int yy_accept[241] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    4,    6,    8,
       11,   14,   17,   20,   22,   25,   28,   31,   34,   37,
       40,   43,   46,   50,   55,   58,   61,   64,   67,   70,
       73,   76,   79,   82,   85,   88,   91,   94,   97,  100,
      103,  106,  109,  112,  115,  118,  121,  124,  127,  129,
      132,  135,  137,  138,  140,  142,  144,  146,  147,  149,
      150,  151,  152,  153,  154,  155,  159,  160,  160,  160,
      160,  160,  160,  160,  163,  164,  165,  166,  167,  167,
      168,  169,  170,  171,  172,  173,  174,  176,  177,  178,
      179,  180,  182,  184,  185,  186,  188,  189,  190,  191,

      192,  193,  194,  195,  196,  196,  197,  198,  199,  200,
      201,  202,  203,  204,  205,  206,  207,  208,  209,  210,
      211,  212,  213,  214,  215,  216,  220,  221,  221,  223,
      223,  224,  224,  224,  225,  227,  227,  229,  229,  231,
      232,  232,  232,  232,  232,  232,  235,  236,  237,  238,
      239,  240,  242,  243,  244,  246,  247,  249,  250,  252,
      254,  256,  257,  258,  259,  260,  261,  262,  263,  263,
      264,  265,  266,  267,  267,  271,  272,  274,  275,  276,
      278,  279,  280,  280,  282,  283,  284,  286,  287,  288,
      290,  291,  292,  293,  294,  295,  296,  298,  299,  300,

      301,  303,  304,  306,  308,  309,  310,  310,  312,  313,
      314,  315,  316,  318,  319,  320,  321,  322,  323,  325,
      327,  328,  329,  331,  333,  334,  336,  338,  339,  341,
      343,  345,  345,  347,  348,  350,  351,  352,  353,  353
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,    1,   20,   21,
       22,   23,   24,   25,   26,   27,   26,   28,   29,   26,
       30,   30,   30,   30,   30,   30,   30,   30,   31,   30,
       30,   30,   30,   30,   30,   30,   30,   32,   30,   30,
       33,   34,   35,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   46,   47,   46,   48,
       49,   50,   46,   51,   52,   53,   54,   55,   56,   57,
       46,   46,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    2,    1,    3,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    5,    1,
        1,    1,    1,    1,    6,    5,    5,    5,    5,    7,
        7,    7,    1,    4,    1,    8,    9,    9,    9,    9,
        9,    9,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    4,    1,    4
    } ;

static yyconst short int yy_base[258] =
    {   0,
        0,  490,  508,   59,   60,   64,  509,  640,  640,  486,
      640,    0,  640,  499,  640,  640,  495,  640,  640,  640,
      490,  640,  111,   56,  640,  480,  479,  473,  456,    0,
      640,  640,    0,  426,  432,  425,   22,   29,   30,   36,
       39,  419,  428,   41,   39,  419,  422,  640,  405,  640,
       64,    0,  640,  412,    0,  640,  391,  165,  640,  640,
        0,  640,  640,  425,   87,   95,  118,   83,  127,  148,
      139,  402,  207,  160,  154,  404,  396,  640,    0,    0,
        0,    0,  377,  364,  343,  335,    0,  324,  322,  301,
      281,    0,    0,  271,  269,    0,  268,  260,  251,  259,

      219,  210,  217,  640,  220,    0,  200,    0,  640,  640,
       99,  640,  640,  640,  640,  640,  640,  640,  640,  640,
      640,  249,  640,  168,  640,  213,  175,  234,  224,  238,
      263,  266,  253,  276,  280,  287,  210,  208,  292,  301,
      297,  307,  313,  206,  322,  328,  334,  640,  640,    0,
        0,    0,  192,  184,  188,   46,    0,  176,    0,    0,
        0,  167,  177,  174,  166,  171,  165,  161,  162,  160,
      241,  355,    0,  342,  349,  318,  339,  362,  370,  372,
      383,  393,  397,  387,  404,  408,  162,  159,  152,  414,
      418,  429,    0,  132,  110,  110,    0,  111,  109,   97,

        0,   90,    0,    0,   86,   85,   78,    0,  640,  640,
      439,  425,  435,  443,  446,  467,  471,  475,  460,   85,
       74,   72,    0,    0,   66,    0,    0,   53,    0,    0,
        0,   48,  481,   53,    0,  640,   65,  640,  640,  517,
      527,  537,  542,  548,  554,  564,  574,  580,  582,  588,
      598,  604,  609,  614,  620,  625,  630
    } ;

static yyconst short int yy_def[258] =
    {   0,
      239,    1,  240,  240,  241,  241,  239,  239,  239,  239,
      239,  242,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  243,  244,
      239,  239,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  239,  239,  239,
      239,  246,  239,  246,  247,  239,  239,  239,  239,  239,
      242,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  248,  239,  239,  239,  239,  239,  239,  249,  250,
      244,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  239,  239,  246,  246,  247,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  251,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  252,  253,  239,  239,
      239,  239,  239,  253,   73,  239,  239,  239,  239,  254,
      250,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  239,  246,
      239,  251,  255,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  252,  256,  257,  239,
      239,  239,  254,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  239,  246,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  256,
      257,  257,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  239,  239,  245,  245,  239,  245,  239,    0,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239
    } ;

static yyconst short int yy_nxt[701] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   25,
       26,   27,   28,    8,   29,   30,   30,   30,   30,   30,
       30,   30,   31,    8,   32,   33,   34,   35,   36,   37,
       38,   39,   33,   33,   40,   33,   33,   41,   42,   33,
       43,   44,   45,   46,   33,   47,   33,   48,   49,   50,
       53,   53,   86,   56,   57,   53,   90,   56,   57,   65,
       87,   74,   74,   74,   74,   88,   89,   92,   91,   94,
       54,   98,  100,   93,   70,   77,  197,   95,  238,  101,
      198,   75,  237,   58,   99,  236,   70,   58,  129,  129,

      235,  105,  124,  124,  124,  124,  234,  221,  125,  221,
      126,  126,  126,   67,  171,  171,  171,   59,  130,   59,
      188,   59,  232,   59,   65,  231,   66,   66,   66,   67,
      127,  125,  230,   67,   67,   67,   67,   68,   69,   70,
      229,   71,   72,  131,  131,  131,   73,  228,   68,  227,
       69,   70,  226,  128,  135,  135,  135,  225,  133,   71,
      133,  224,  132,  134,  134,  134,  134,   72,  110,  146,
      146,  146,  146,   65,  136,   74,   74,   74,   74,  223,
      111,  111,  111,  124,  124,  124,  124,  221,   70,  147,
      175,  175,  175,  140,  221,   75,   70,  188,  112,  208,

       70,  113,  114,  174,  207,  115,  116,  206,   70,  205,
      176,  204,  117,  203,  202,  118,  119,  120,  201,  121,
      200,  122,  139,  139,  139,  140,  125,  199,  126,  126,
      126,   67,  196,  141,  142,  195,  194,  143,  144,  177,
      177,  138,  145,  138,  141,  188,  142,  170,  127,  140,
      140,  140,  140,  179,  179,  143,  209,  209,  209,  178,
      169,  168,  167,  144,  173,  173,  173,  173,  134,  134,
      134,  134,  166,  130,  173,  173,  173,  173,  180,  180,
      180,  180,  182,  182,  182,  173,  173,  173,  173,  173,
      173,  134,  134,  134,  134,  184,  184,  184,  181,  165,

      164,  132,  186,  186,  186,  125,  163,  190,  190,  190,
      140,  183,  179,  179,  125,  185,  140,  140,  140,  140,
      162,  161,  136,  182,  182,  182,  160,  191,  186,  186,
      186,  159,  130,  212,  212,  212,  128,  186,  186,  186,
      239,   65,  132,  146,  146,  146,  146,  158,  136,  192,
      192,  192,  192,  176,  177,  177,   70,  211,  211,  211,
      211,  157,  125,   75,  175,  175,  175,  140,   70,  147,
      239,  239,  239,  239,  178,  156,  155,  213,  213,  154,
      239,  239,  239,  239,  127,  215,  215,  180,  180,  180,
      180,  239,  239,  239,  239,  239,  239,  214,  217,  217,

      217,  217,  184,  184,  184,  214,  153,  216,  217,  217,
      217,  217,  218,  218,  218,  218,  152,  149,  181,  219,
      219,  219,  185,  212,  212,  212,  148,  125,  181,  190,
      190,  190,  140,  190,  190,  190,  140,  138,  123,  176,
      212,  212,  212,  176,  192,  192,  192,  192,  109,  191,
      213,  213,  107,  176,  211,  211,  211,  211,  215,  215,
      176,  215,  215,  104,  147,  103,  102,   70,   97,   96,
      178,   85,   84,   83,  174,  219,  219,  219,  214,   70,
       79,  214,  233,  233,  233,  233,  217,  217,  217,  217,
      218,  218,  218,  218,   78,  185,  233,  233,  233,  233,

       77,   76,  181,   64,   63,   62,  181,   60,  239,   53,
      183,   51,  239,  239,  239,  239,  216,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   61,  239,   61,
       61,   61,   61,   61,   61,   61,   61,   80,  239,   80,
       80,   80,   81,  239,   81,   81,   81,   81,   82,  239,
       82,   82,   82,   82,  106,  239,  106,  106,  106,  106,
      106,  106,  106,  106,  108,  239,  239,  239,  108,  108,
      108,  108,  108,  108,  137,  239,  239,  137,  137,  150,
      150,  150,  151,  239,  151,  151,  151,  151,  172,  239,

      239,  172,  172,  172,  172,  172,  172,  172,  187,  239,
      239,  187,  187,  189,  239,  239,  189,  189,  193,  239,
      193,  193,  193,  193,  210,  239,  239,  239,  210,  220,
      239,  239,  220,  220,  222,  239,  239,  222,  222,    7,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239

    } ;

static yyconst short int yy_chk[701] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    5,   37,    5,    5,    6,   39,    6,    6,   24,
       37,   24,   24,   24,   24,   38,   38,   40,   39,   41,
        4,   44,   45,   40,   24,   51,  156,   41,  237,   45,
      156,   24,  234,    5,   44,  232,   24,    6,   68,   68,

      228,   51,   65,   65,   65,   65,  225,  222,   66,  221,
       66,   66,   66,   66,  111,  111,  111,    5,   68,    5,
      220,    6,  207,    6,   23,  206,   23,   23,   23,   23,
       66,   67,  205,   67,   67,   67,   67,   23,   23,   23,
      202,   23,   23,   69,   69,   69,   23,  200,   23,  199,
       23,   23,  198,   67,   71,   71,   71,  196,   70,   23,
       70,  195,   69,   70,   70,   70,   70,   23,   58,   75,
       75,   75,   75,   74,   71,   74,   74,   74,   74,  194,
       58,   58,   58,  124,  124,  124,  124,  189,   74,   75,
      127,  127,  127,  127,  188,   74,  124,  187,   58,  170,

       74,   58,   58,  124,  169,   58,   58,  168,  124,  167,
      127,  166,   58,  165,  164,   58,   58,   58,  163,   58,
      162,   58,   73,   73,   73,   73,  126,  158,  126,  126,
      126,  126,  155,   73,   73,  154,  153,   73,   73,  129,
      129,  144,   73,  138,   73,  137,   73,  107,  126,  128,
      128,  128,  128,  130,  130,   73,  171,  171,  171,  129,
      105,  103,  102,   73,  122,  122,  122,  122,  133,  133,
      133,  133,  101,  130,  122,  122,  122,  122,  131,  131,
      131,  131,  132,  132,  132,  122,  122,  122,  122,  122,
      122,  134,  134,  134,  134,  135,  135,  135,  131,  100,

       99,  132,  136,  136,  136,  139,   98,  139,  139,  139,
      139,  134,  141,  141,  140,  135,  140,  140,  140,  140,
       97,   95,  136,  142,  142,  142,   94,  139,  143,  143,
      143,   91,  141,  176,  176,  176,  140,  145,  145,  145,
      145,  146,  142,  146,  146,  146,  146,   90,  143,  147,
      147,  147,  147,  176,  177,  177,  146,  174,  174,  174,
      174,   89,  175,  146,  175,  175,  175,  175,  146,  147,
      172,  172,  172,  172,  177,   88,   86,  178,  178,   85,
      172,  172,  172,  172,  175,  179,  179,  180,  180,  180,
      180,  172,  172,  172,  172,  172,  172,  178,  181,  181,

      181,  181,  184,  184,  184,  179,   84,  180,  182,  182,
      182,  182,  183,  183,  183,  183,   83,   77,  181,  185,
      185,  185,  184,  186,  186,  186,   76,  190,  182,  190,
      190,  190,  190,  191,  191,  191,  191,   72,   64,  185,
      212,  212,  212,  186,  192,  192,  192,  192,   57,  190,
      213,  213,   54,  191,  211,  211,  211,  211,  214,  214,
      212,  215,  215,   49,  192,   47,   46,  211,   43,   42,
      213,   36,   35,   34,  211,  219,  219,  219,  214,  211,
       29,  215,  216,  216,  216,  216,  217,  217,  217,  217,
      218,  218,  218,  218,   28,  219,  233,  233,  233,  233,

       27,   26,  216,   21,   17,   14,  217,   10,    7,    3,
      218,    2,    0,    0,    0,    0,  233,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  242,    0,  242,
      242,  242,  242,  242,  242,  242,  242,  243,    0,  243,
      243,  243,  244,    0,  244,  244,  244,  244,  245,    0,
      245,  245,  245,  245,  246,    0,  246,  246,  246,  246,
      246,  246,  246,  246,  247,    0,    0,    0,  247,  247,
      247,  247,  247,  247,  248,    0,    0,  248,  248,  249,
      249,  249,  250,    0,  250,  250,  250,  250,  251,    0,

        0,  251,  251,  251,  251,  251,  251,  251,  252,    0,
        0,  252,  252,  253,    0,    0,  253,  253,  254,    0,
      254,  254,  254,  254,  255,    0,    0,    0,  255,  256,
        0,    0,  256,  256,  257,    0,    0,  257,  257,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "RubyLexer.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 6 "RubyLexer.l"
	#include <stdio.h> 
    #include <string.h>   
    #include "parser.tab.h"
    void removeCharacterFromString(const char * str, char * dest, char deleted_char);
    int btoi(const char * str);
#define ML_COMMENT 1

#define STRING 2

#line 663 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 28 "RubyLexer.l"


   
    int num;
    float real_num;
    char temp1[100];
    char temp2[100];
    char comment[1000];
    char string[1000];
    int concatenation = 0;


#line 830 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 240 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 640 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 40 "RubyLexer.l"
{ 
                  printf("Keyword: and\n");
                 
                }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 44 "RubyLexer.l"
{ printf("Keyword: begin\n"); return BEGIN_KEYWORD; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "RubyLexer.l"
{ printf("Keyword: class\n"); return CLASS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "RubyLexer.l"
{ printf("Keyword: new\n"); return NEW; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "RubyLexer.l"
{ printf("Keyword: def\n"); return DEF; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "RubyLexer.l"
{ printf("Keyword: defined?\n"); return DEFINED; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "RubyLexer.l"
{ printf("Keyword: do\n"); return DO; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "RubyLexer.l"
{ printf("Keyword: if\n"); return IF; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "RubyLexer.l"
{ printf("Keyword: else\n"); return ELSE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "RubyLexer.l"
{ printf("Keyword: elsif\n"); return ELSIF; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "RubyLexer.l"
{ printf("Keyword: end\n"); return END; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "RubyLexer.l"
{ printf("Keyword: false\n"); return FALSE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "RubyLexer.l"
{ printf("Keyword: for\n"); return FOR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "RubyLexer.l"
{ printf("Keyword: in\n"); return IN; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "RubyLexer.l"
{ printf("Keyword: not\n"); return NOT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "RubyLexer.l"
{ printf("Keyword: or\n"); return OR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "RubyLexer.l"
{ printf("Keyword: return\n"); return RETURN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "RubyLexer.l"
{ printf("Keyword: self\n"); return SELF; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "RubyLexer.l"
{ printf("Keyword: super\n"); return SUPER; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "RubyLexer.l"
{ printf("Keyword: then\n"); return THEN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "RubyLexer.l"
{ printf("Keyword: true\n"); return TRUE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "RubyLexer.l"
{ printf("Keyword: until\n"); return UNTIL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "RubyLexer.l"
{ printf("Keyword: while\n"); return WHILE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 68 "RubyLexer.l"
{ printf("Operator: +\n"); return ARITHMETIC_PLUS_OP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 69 "RubyLexer.l"
{ printf("Operator: -\n"); return ARITHMETIC_MINUS_OP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 70 "RubyLexer.l"
{ printf("Operator: *\n"); return ARITHMETIC_MUL_OP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 71 "RubyLexer.l"
{ printf("Operator: /\n"); return ARITHMETIC_DIV_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 72 "RubyLexer.l"
{ printf("Operator: %%\n"); return ARITHMETIC_MOD_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 73 "RubyLexer.l"
{ printf("Operator: **\n"); return ARITHMETIC_POW_OP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 75 "RubyLexer.l"
{ printf("Operator: ==\n"); return EQL_OP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 76 "RubyLexer.l"
{ printf("Operator: !=\n"); return NOT_EQL_OP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 77 "RubyLexer.l"
{ printf("Operator: >\n"); return GREATER_OP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 78 "RubyLexer.l"
{ printf("Operator: <\n"); return LESS_OP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "RubyLexer.l"
{ printf("Operator: >=\n"); return GREATER_OR_EQL_OP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "RubyLexer.l"
{ printf("Operator: <=\n"); return LESS_OR_EQL_OP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "RubyLexer.l"
{ printf("Operator: <=>\n"); return COMB_COMPRASION_OP; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "RubyLexer.l"
{ printf("Operator: ===\n"); return CASE_EQL_OP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 84 "RubyLexer.l"
{ printf("Operator: =\n"); return ASSIGN_OP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 86 "RubyLexer.l"
{ printf("Operator: &&\n"); return LOGICAL_AND_OP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 87 "RubyLexer.l"
{ printf("Operator: ||\n"); return LOGICAL_OR_OP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 88 "RubyLexer.l"
{ printf("Operator: !\n"); return LOGICAL_NOT_OP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 90 "RubyLexer.l"
{ printf("Operator: ..\n"); return INCLUSIVE_RANGE_OP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 91 "RubyLexer.l"
{ printf("Operator: ...\n"); return EXCLUSIVE_RANGE_OP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 93 "RubyLexer.l"
{ return NEW_LINE_SYMBOL;  }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 94 "RubyLexer.l"
{ return DOT_SYMBOL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 95 "RubyLexer.l"
{ return COMMA_SYMBOL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 96 "RubyLexer.l"
{ return SEMICOLON_SYMBOL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 97 "RubyLexer.l"
{ return OPEN_ROUND_BRACKET; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 98 "RubyLexer.l"
{ return CLOSE_ROUND_BRACKET; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 99 "RubyLexer.l"
{ return OPEN_CURLY_BRACKET; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 100 "RubyLexer.l"
{
                if(concatenation == 0) {
                    return CLOSE_CURLY_BRACKET;
                } else {
                    concatenation--;
                    BEGIN(STRING);
                    string[0] = 0;
                    return ARITHMETIC_PLUS_OP;
                }
            }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 110 "RubyLexer.l"
{ return OPEN_SQUARE_BRACKET; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 111 "RubyLexer.l"
{ return CLOSE_SQUARE_BRACKET; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 112 "RubyLexer.l"
{ return COMMERCIAL_AT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 113 "RubyLexer.l"
{ 
                string[0] = 0; 
                BEGIN(STRING);    
            }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "RubyLexer.l"
{ 
                        printf("String: %s\n", string);
                        printf("Found concatenation with string\n");
                        concatenation++;
                        BEGIN(INITIAL);
                    }            
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 126 "RubyLexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 127 "RubyLexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 128 "RubyLexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 129 "RubyLexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 130 "RubyLexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 131 "RubyLexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 132 "RubyLexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 "RubyLexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 "RubyLexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 135 "RubyLexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 "RubyLexer.l"
{ strcat(string, "\\"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 137 "RubyLexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 138 "RubyLexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 146 "RubyLexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 153 "RubyLexer.l"
{ printf("ERROR: invalid hex escape \n"); } 
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 154 "RubyLexer.l"
{ printf("ERROR: expected \" \n");}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 155 "RubyLexer.l"
{ printf("String: %s\n", string); BEGIN(INITIAL); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 157 "RubyLexer.l"
{ printf("Single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 159 "RubyLexer.l"
{                                     
                            comment[0] = 0; 
                            BEGIN(ML_COMMENT);
                        }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 164 "RubyLexer.l"
{
                            strcat(comment, yytext+4);
                            printf("Multi-line comment: %s\n", comment);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 170 "RubyLexer.l"
{ 
                            strcat(comment, yytext); 
                        }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 174 "RubyLexer.l"
{ 
                            printf("expected =end"); BEGIN(INITIAL); 
                        }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 178 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 1,temp1,'_');
                                num = strtoll(temp1, NULL, 8);
                                printf("Binary number: %d\n", num);
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 185 "RubyLexer.l"
{ 
                                removeCharacterFromString(yytext,temp1,'_');
                                num = atoi(temp1);
                                printf("Decimal number: %d\n", num);
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 192 "RubyLexer.l"
{ printf("ERROR: invalid decimal number: %s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 194 "RubyLexer.l"
{
                                removeCharacterFromString(yytext+2,temp1,'_');
                                num = atoi(temp1);
                                printf("Decimal number: %d\n", num);    
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 201 "RubyLexer.l"
{ printf("ERROR: invalid decimal number with dD: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 203 "RubyLexer.l"
{
                                removeCharacterFromString(yytext,temp1,'_');
                                removeCharacterFromString(temp1,temp2,'o');
                                removeCharacterFromString(temp2,temp1,'O');
                                sscanf(temp1,"%o",&num);
                                printf("Octal number: %d\n", num);
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 212 "RubyLexer.l"
{ printf("ERROR: invalid octal number: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 214 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                sscanf(temp1,"%x",&num);
                                printf("Hexadecimal number: %d\n", num);
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 221 "RubyLexer.l"
{ printf("ERROR: invalid hexadecimal number: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 223 "RubyLexer.l"
{
                                removeCharacterFromString(yytext + 2,temp1,'_');
                                num = btoi(temp1);
                                printf("Binary number: %d\n", num); 
                                return INTEGER_NUMBER; 
                            }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 230 "RubyLexer.l"
{ printf("ERROR: invalid binary number: %s\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 233 "RubyLexer.l"
{
                                                                 removeCharacterFromString(yytext,temp1,'_'); 
                                                                 real_num = atof(temp1);                                                                
                                                                 printf("Float number: %f\n", real_num);
                                                                 return FLOAT_NUMBER;
                                                            }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 240 "RubyLexer.l"
{
                                                printf("Local variable or method name: %s\n", yytext);
                                                return VAR_OR_METHOD_NAME;
                                            }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 245 "RubyLexer.l"
{
                                                printf("Instance variable: %s\n", yytext);
                                                return INSTANCE_VAR_NAME;
                                            }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 250 "RubyLexer.l"
{
                                                printf("Class variable: %s\n", yytext);
                                                return CLASS_VAR_NAME;
                                            }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 255 "RubyLexer.l"
{
                                                printf("Class name: %s\n", yytext);
                                                return CLASS_NAME;
                                            }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 260 "RubyLexer.l"
{}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 262 "RubyLexer.l"
ECHO;
	YY_BREAK
#line 1497 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 240 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 240 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 239);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 262 "RubyLexer.l"


void removeCharacterFromString(const char * str, char * dest, char deleted_char) {
	int j = 0;
	
    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int btoi(const char * str) {
    const char *p = str;
    unsigned int   r = 0;

    while (p && *p ) {
        r <<= 1;
        r += (unsigned int)((*p++) & 0x01);
    }

    return (int) r;
}

int main(int argc, char **argv ){
	yyin = fopen(argv[1], "r" );

    yylex();
    return 0;
}
