a = 4.8
b = 2.0
print("4.8 + 2.0 = ")
print(a + b)
print("\n")
print("4.8 - 2.0 = ")
print(a - b)
print("\n")
print("4.8 * 2.0 = ")
print(a * b)
print("\n")
print("4.8 / 2.0 = ")
print(a / b)
print("\n")
print("4.8 > 2.0 = ")
print(a > b)
print("\n")
print("4.8 >= 2.0 = ")
print(a >= b)
print("\n")
print("4.8 < 2.0 = ")
print(a < b)
print("\n")
print("4.8 <= 2.0 = ")
print(a <= b)
print("\n")
print("4.8 == 2.0 = ")
print(a == b)
print("\n")
print("4.8 != 2.0 = ")
print(a != b)
print("\n")

